-- 코드를 입력하세요
SELECT B.BOOK_ID, A.AUTHOR_NAME, date_format(B.PUBLISHED_DATE,"%Y-%m-%d") as PUBLISHED_DATE
FROM BOOK B, AUTHOR A
WHERE B.CATEGORY = '경제'
  AND A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY B.PUBLISHED_DATE
