-- BOOK B, AUTHOR A, BOOK_SALES BS
-- 책을 쓴 저자를 join --> BOOK과 AUTHOR 조인
-- 책의 판매량 join --> BOOK과 BOOK_SALES 조인
SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * BS.SALES) AS TOTAL_SALES

FROM AUTHOR A
         INNER JOIN BOOK B ON A.AUTHOR_ID = B.AUTHOR_ID
         INNER JOIN BOOK_SALES BS ON BS.BOOK_ID = B.BOOK_ID
WHERE BS.SALES_DATE LIKE ("2022-01%")
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC