
select FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
from REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, max(favorites)
    from REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC