-- 코드를 입력하세요
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, date_format(B.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE A
         JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID  = (
    SELECT B.MEMBER_ID
    FROM REST_REVIEW B
    GROUP BY B.MEMBER_ID
    ORDER BY COUNT(*) DESC LIMIT 1
    )
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT

