SELECT CATEGORY, PRICE as MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE IN (
    SELECT max(PRICE)
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) AND CATEGORY IN ('식용유', '김치', '국', '과자')
ORDER BY MAX_PRICE DESC