-- 코드를 입력하세요
-- July 테이블에서 FLAVOR 별로 sum을 구해라
-- FIRST_HALF에서 FLAVOR가 같은 것과 TOTAL_ORDER를 더해서 DESC

-- 1.
SELECT A.FLAVOR
FROM FIRST_HALF A
         JOIN (select FLAVOR, sum(TOTAL_ORDER) AS TOTAL_ORDER
               FROM JULY
               GROUP BY FLAVOR) B
              ON A.FLAVOR = B.FLAVOR
ORDER BY A.TOTAL_ORDER + B.TOTAL_ORDER DESC
    LIMIT 3

-- 2.
SELECT A.FLAVOR
FROM FIRST_HALF A
         JOIN JULY B ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY (A.TOTAL_ORDER + sum(B.TOTAL_ORDER))
        DESC LIMIT 3